//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datainfo
    {
        public string Indicator { get; set; }
        public string MCH { get; set; }
        public string MCHC { get; set; }
        public string MCV { get; set; }
        public string RDW { get; set; }
        public string Базофилыабс { get; set; }
        public string Базофилыотн { get; set; }
        public string Лейкоциты { get; set; }
        public string Лимфоцитыабс { get; set; }
        public string Лимфоцитыотн { get; set; }
        public string Гематокрит { get; set; }
        public string Гемоглобин { get; set; }
        public string Моноцитыабс { get; set; }
        public string Моноцитыотн { get; set; }
        public string Тромбоцитыабс { get; set; }
        public string Тромбоцитыотн { get; set; }
        public string Нейтрофилыабс { get; set; }
        public string Нейтрофилыотн { get; set; }
        public string СОЭ { get; set; }
        public string Эозинофилыабс { get; set; }
        public string Эозинофилыотн { get; set; }
        public string Эритроциты { get; set; }
    }
}
