//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicators
    {
        public string Indicator { get; set; }
        public string C1д_2дЖ { get; set; }
        public string C1д_2дМ { get; set; }
        public string C2д_3дЖ { get; set; }
        public string C2д_3дМ { get; set; }
        public string C3д_4дЖ { get; set; }
        public string C3д_4дМ { get; set; }
        public string C4д_5дЖ { get; set; }
        public string C4д_5дМ { get; set; }
        public string C5д_14дЖ { get; set; }
        public string C5д_14дМ { get; set; }
        public string C14д_15дЖ { get; set; }
        public string C14д_15дМ { get; set; }
        public string C15д_4нЖ { get; set; }
        public string C15д_4нМ { get; set; }
        public string C4н_4_3нЖ { get; set; }
        public string C4н_4_3нМ { get; set; }
        public string C4_3н_8_6нЖ { get; set; }
        public string C4_3н_8_6нМ { get; set; }
        public string C8_6н_4мЖ { get; set; }
        public string C8_6н_4мМ { get; set; }
        public string C4м_6мЖ { get; set; }
        public string C4м_6мМ { get; set; }
        public string C6м_9мЖ { get; set; }
        public string C6м_9мМ { get; set; }
        public string C9м_12мЖ { get; set; }
        public string C9м_12мМ { get; set; }
        public string C12м_2гЖ { get; set; }
        public string C12м_2гМ { get; set; }
        public string C2л_3гЖ { get; set; }
        public string C2л_3гМ { get; set; }
        public string C3г_4гЖ { get; set; }
        public string C3г_4гМ { get; set; }
        public string C4г_5лЖ { get; set; }
        public string C4г_5лМ { get; set; }
        public string C5л_6лЖ { get; set; }
        public string C5л_6лМ { get; set; }
        public string C6л_7л { get; set; }
        public string C7л_9л { get; set; }
        public string C9л_10л { get; set; }
        public string C10л_11л { get; set; }
        public string C11л_12л { get; set; }
        public string C12л_15лЖ { get; set; }
        public string C12л_15лМ { get; set; }
        public string C15л_16лЖ { get; set; }
        public string C15л_16лМ { get; set; }
        public string C16л_18лЖ { get; set; }
        public string C16л_18лМ { get; set; }
        public string C18л_21гЖ { get; set; }
        public string C18л_21гМ { get; set; }
        public string C21г_45лЖ { get; set; }
        public string C21г_45лМ { get; set; }
        public string C45л_50лЖ { get; set; }
        public string C45л_50лМ { get; set; }
        public string C50л_65лЖ { get; set; }
        public string C50л_65лМ { get; set; }
        public string C65л_120лЖ { get; set; }
        public string C65л_120лМ { get; set; }
    }
}
