//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbaseEntities : DbContext
    {
        private static DbaseEntities _context;

        public DbaseEntities()
            : base("name=DbaseEntities")
        {
        }
        public static DbaseEntities GetContext()
        {
            if (_context == null)
                _context = new DbaseEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datainfo> Datainfo { get; set; }
        public virtual DbSet<Indicators> Indicators { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
