//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public string Дата { get; set; }
        public Nullable<float> MCH { get; set; }
        public Nullable<float> MCHC { get; set; }
        public Nullable<float> MCV { get; set; }
        public Nullable<float> RDW { get; set; }
        public Nullable<float> Базофилыабс { get; set; }
        public Nullable<float> Баззофилыотн { get; set; }
        public Nullable<float> Гематокрит { get; set; }
        public Nullable<float> Гемоглобин { get; set; }
        public Nullable<float> Лейкоциты { get; set; }
        public Nullable<float> Лимфоцитыабс { get; set; }
        public Nullable<float> Лимфоцитыотн { get; set; }
        public Nullable<float> Моноцитыабс { get; set; }
        public Nullable<float> Моноцитыотн { get; set; }
        public Nullable<float> Нейтрофилыабс { get; set; }
        public Nullable<float> Нейтрофилыотн { get; set; }
        public Nullable<float> СОЭ { get; set; }
        public Nullable<float> Тромбоциты { get; set; }
        public Nullable<float> Эозинофилыабс { get; set; }
        public Nullable<float> Эозинофилыотн { get; set; }
        public Nullable<float> Эритроциты { get; set; }
    }
}
